### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by shagu** [hobbyquaker/r-test#2]
请添加许可证文件

**Comment by hobbyquaker** [comment]
ਇਹ ਇਰਾਦਾ ਨਾਲ ਇਕ ਗੈਰ-ਲਾਇਸੰਸਸ਼ੁਦਾ ਪ੍ਰਾਜੈਕਟ ਹੈ. ਕਿਸੇ ਨੂੰ ਇਸ ਦੀ ਵਰਤੋਂ ਨਹੀਂ ਕਰਨੀ ਚਾਹੀਦੀ.

**Comment by johndoe31415** [comment]
良い解決策ではありません。問題を再度開いてください。
